# Generated by Django 2.2.3 on 2020-01-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotapp', '0004_auto_20200104_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manko',
            fields=[
                ('list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotapp.List')),
                ('manko_id', models.CharField(max_length=10)),
            ],
            bases=('hotapp.list',),
        ),
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AlterModelManagers(
            name='list',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='list',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
